language: node_js
node_js: node
deploy: desolate-forest-36768
  provider: heroku
  api_key:
    secure: xk3z43sBbY9gshzuoyHpLVS3tNBL80TAWZuwAzoMISMdoEC9+3Ooz/vcjxAK972V/MVnpwf27hCXZ302INCHdN5ZPzkPM/nM0C8roVuluqboxu16N7I/fXYrbQYNHP2fzAH6DSRcCQntHgAzD7UjJe9BEzIs8GjhL+LLRyQBz5MTJuUS3DOImlmnQPWi4j2y8f7rZnbws6ToQhlpFme6sGZct4UyWWtkySlTXR7EhXuyvUC3QgceaBL8xM1y2TJ/61EggfHqX742CSg03ss3wNhr1m8tZKAqmmey5Y2/jarBkcFm99PSdFbiLSR44SkQdbTx9FOzloRhPpb9OPtr9jyq8K+WkWGzCVMNZ+E27rRKgmugShn2JBuiZ3oVl7RCK5CXKFztUGvLToAMdFWbCsaK9eNXNQseTEmRKdwoQ8znuAW2ph4EUpcPTeZLGetfNrQ7uP7jBaVd0kVveE/Qc4kNeldDvJ8xmQOrxGF7B2ea1JdcA2OaNvcTjS3sgs9yYqac0bT8ipXvVynBfNHih4krDTG92Cdfw9rVii7rk689hNRPnTLrW9OZCk4ENe5RjSp9vUKPsJjSn2NAtfcNDek0W9t7oALWMSj7GNr1P7Et/kXTXplLA/i6ybk/H8pN9bEzqcjaW/M/Ar6DnihTdDC+O4O4IvJxspdpjVgwMzE=
  app: node-shopping-list-integration-tests
  on:
    repo: rosaxny/node-shopping-list-integration-tests
